#! /bin/bash


MAX_SEQ_LENGTH=128
PER_DEVICE_TRAIN_BATCH_SIZE=128
LEARNING_RATE=2e-5
NUM_TRAIN_EPOCHS=10
STEPS=50
OUTPUT_DIR=../output/${PROJECT_NAME}/
LOG_DIR=../logs/${PROJECT_NAME}/
EARLY_STOPPING_STEP=5
